version: '3'

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
  
  localstack:
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3,dynamodb,sqs
      - DEBUG=1
